---
# control
control:
  data_name: ML100K
  data_mode: explicit
  model_name: mf
  sigma: 0.1
  semi_mode: fix
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
