---
# control
#control:
# data
data_name: MovieLens100k
model_name: mf
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
