---
# control
control:
  data_name: ML100K
  data_mode: user
  target_mode: explicit
  model_name: ae
  data_split_mode: random
  train_mode: joint
  match_ratio: 1
  cold_start_ratio: 1
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
